name: xmake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: 2.7.7  # Replace with the desired xmake version.

    - name: Update Submodules
      # Update 3rdparty libraries as submodule
      run: git submodule update --init --recursive

    - name: Configure xmake
      # Configure xmake with platform and build type
      run: xmake config -a x64 -m release --build_python=true

    - name: Build
      # Build your program with the given configuration
      run: xmake -w --all

    - name: Test
      # working-directory: ${{github.workspace}}/build
      run: xmake run test-layer

